name: learn-github-actions
on: [push]
jobs:
  check-bats-version:
    runs-on: ubuntu-latest
    container:
      image: kiwabuchi/metall_test:centos7_min
    steps:
      - uses: actions/checkout@v2
      - name: Log the node version
        run: |
          ls -ls /
          cat /etc/os-release
